### ISSUE TITLE
"Sites location missing" message odd behaviour.

### ISSUE THREAD

**Issue by waj** [instedd/resourcemap#500]
There are some issues related to the "Sites with no location" message. 

a) If the user accesses a collection with sites with no location, the "Sites with no location" message displays. But if the user goes back to the collection's main menu, the message still displays, and it shouldn't. 

b) If the user clicks the message on the collection's main menu, all other collection's sites dissappears, as if a query were launched but the user does not get any visual response. 

c) If after pressing the "Sites with no location" link on the collection's main menu the user then access any collection, the "missing location" filter is applied, no matter if there are or not missing locations. 

Version eac94d41f1c4

---------------------------------------
- Imported from BitBucket: https://bitbucket.org/instedd/resource_map/issue/500
- Originally Reported By: German Batiston
- Originally Created At: 2013-06-24 15:06:23+00:00

**Comment by mmuller** [comment]
Ok in version 2.17-pre1
