### ISSUE TITLE
'Upload new logo' input not working correctly

### ISSUE THREAD

**Issue by pmallol** [instedd/resourcemap#796]
Found in v2.14-pre2

1. Go to 'Collections'
2. Click on 'Create new collection'
3. Under the 'Upload new logo' title, click the "Choose File" button 
4. Choose an image and click 'Save'

Obtained: the 'Upload new logo' input does nothing and a 500 error appears in the console. Nevertheless, if you click the 'Collection' tab without clicking the 'Save' button in the 'Create new collection' page, a new collection appears in the left panel with the name "My collection", and if you click it, the image for the new logo was indeed successfully uploaded.

Expected: the image chosen should appear in a little preview square under the 'Logo' title and a button with the word 'Adjust' should appear under it. (See screenshot below)
![screen shot 2014-11-13 at 5 47 45 pm](https://cloud.githubusercontent.com/assets/9214460/5036270/39b0c6aa-6b5d-11e4-9d90-81fa0781625d.png)

*Note that if you try several times to upload a logo (steps 3. and 4.) without success while creating the new collection and click the 'Collections' tab, now several new collections with the default name "My collection" appear in the left panel, even though the 'Collection Name' input can't be black when creating  a new collection.

![screen shot 2014-11-13 at 5 11 52 pm 500 error](https://cloud.githubusercontent.com/assets/9214460/5036335/b0039576-6b5d-11e4-8bcc-adcf10dab74d.png)

**Comment by ggiraldez** [comment]
Fixed by 59d86027feb37d767a32ced29cdecbf110ae9518 and 3968f01c5ad6ac3964f00154e6e7e93d0092ac3a.

**Comment by mmuller** [comment]
Ok in version 2.16.2
