### ISSUE TITLE
Preview from uploaded image does not match the crop tracker exactly

### ISSUE THREAD

**Issue by pmallol** [instedd/resourcemap#803]
Found in version 2.13.3

1. Navigate to Collections tab
2. Click 'Create collection'
3. Fill 'Name' with [name]
4. Upload new logo by clicking the 'Choose File' button and selecting an image from the computer
5. Once the upload has finished, click on 'Adjust'

Obtained: the Preview does not match the crop tracker.
Expected: user should be able to modify the selection and the preview should match that.

![screen shot 2014-11-20 at 3 29 14 pm](https://cloud.githubusercontent.com/assets/9214460/5130742/d1349b14-70cb-11e4-840f-5523b05518db.png)

**Comment by ggiraldez** [comment]
This was fixed in 3968f01c5ad6ac3964f00154e6e7e93d0092ac3a
