### ISSUE TITLE
'Phone' field stays on focus in inline edit mode even when other field is selected

### ISSUE THREAD

**Issue by pmallol** [instedd/resourcemap#807]
Found in v2.13.3

Preconditions:
User has some sites in a collection "X" configured with a layer with several fields including a 'Phone' type field named "tel".

1. Navigate to collection "X" and click a site.
2. Click the "tel" input and type: 1144444444
3. Click another layer field's input

Obtained: the input for the "tel" field stays on focus.

Expected: the input should be out of focus as the other fields do when not selected to edit.

![screen shot 2014-11-25 at 1 07 29 pm](https://cloud.githubusercontent.com/assets/9214460/5186508/8022f972-74a5-11e4-8a1a-1dc9526f7668.png)

**Comment by ggiraldez** [comment]
The last two commits should refer to #796, not this issue.

**Comment by mmuller** [comment]
Ok in version 2.16.2
