### ISSUE TITLE
Permissions when name is set to read only

### ISSUE THREAD

**Issue by steesdale** [instedd/resourcemap#811]
Issue: 
A user created multiple layers in a RM collection and set the permissions as follows for a user. 
![screen shot 2014-12-03 at 11 20 43 am](https://cloud.githubusercontent.com/assets/3987608/5283923/d04f2904-7ade-11e4-8405-ea2ae4407195.png)

The user expected that the tool would allow for this user to only update the layer titled "equipment".  Also that they wouldn't be able to create any new sites.  

What happened though is that user couldn't update the layer they have access to.  They were given the following error after making a change to an existing record and selecting done. 
![screen shot 2014-12-03 at 11 27 42 am](https://cloud.githubusercontent.com/assets/3987608/5284022/865947ac-7adf-11e4-840a-7a5259b586fd.png)

**Comment by mmuller** [comment]
@steesdale I couldn't reproduce this issue in version 2.17.2

**Comment by mmuller** [comment]
Reproduced in version 2.17.2

- If the user has no permission to update `Name` and `Location` the button to create a site should be hidden.

- To move the marker on the map the user should have permission to update the `Location`.

**Comment by matiasgarciaisaia** [comment]
> - To move the marker on the map the user should have permission to update the `Location`.

Note for future self: that only happens on the Edit Site panel. If you try to single-edit the Location while viewing the Site, you are correctly not allowed to do so.

**Comment by mmuller** [comment]
It is not working properly in version da54b36

> - If the user has no permission to update Name and Location the button to create a site should be hidden.
> - The user expected that the tool would allow for this user to only update the layer (...). Also that they **wouldn't be able to create any new sites**.

When the user press the button to create a site an error ir thrown.

<img width="1149" alt="screen shot 2017-05-23 at 9 10 50 am" src="https://cloud.githubusercontent.com/assets/518152/26353670/df8a12fa-3f97-11e7-9dc4-50aaae057527.png">

**Comment by mmuller** [comment]
Working properly in version g60a23a0
