### ISSUE TITLE
API Enhancement to Improve Access to Metadata During API Calls

### ISSUE THREAD

**Issue by steesdale** [instedd/resourcemap#815]
Currently: Users have requested improved ability to consume metadata during API calls in a way to reduce number of calls needed when making API calls.  A couple instances are in complex hierarchies or select1/multi-select, where the API/.csv calls will yield the short-codes not the metadata long strings typically needed for presenting this data to human users.  When designing tools that use RM as a data source this becomes a challenge as both the layer design and actual data need to be called. 

Suggestion: Could we review the option to enhance the API to allow for accessing either the code sets or long strings directly or both in the API call of the data directly?   Is there some other solution to this issue that we should consider?  IF this could be reviewed during the routine IP meetings it would be appreciated.  If more user detail is needed, let me know. 

@chadad

**Comment by chadad** [comment]
@MichaelKambenga: 

@vtiffenberg from our team is going to start working on this. 

We have some questions about this.

1. Is this going to be used only to show results or also to make updates? In other words, do you need a new endpoint that exposes the names only or do you need both name and code ?

2. Do you need this for CSV exports as scott said in the first message or do you need it for JSON calls?

**Comment by MichaelKambenga** [comment]
@chadad 
1. Currently,only showing the results will do.
2. In both formats will be a plus for other users who will need it in csv,but currently we need it for JSON calls.

Thanks...

**Comment by pmallol** [comment]
Ok in version 2.14-pre6
