### ISSUE TITLE
Bad index on table during manual install

### ISSUE THREAD

**Issue by litlfred** [instedd/resourcemap#826]
doing a manual install I got an error about a bad index name on a table (see message below) when doing: 
  script/bundle exec rake db:migrate RAILS_ENV=production

== 20120615051700 RenameRepeatColumnToSite: migrating =========================
-- rename_column(:reminders_sites, :repeat_id, :site_id)
   -> 0.1082s
-- remove_index(:reminders_sites, {:column=>:repeat_id})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Index name 'index_reminders_sites_on_repeat_id' on table 'reminders_sites' does not exist/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/schema_statements.rb:819:in `index_name_for_remove'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/schema_statements.rb:559:in `remove_index'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/migration.rb:649:in `block in method_missing'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/migration.rb:621:in `block in say_with_time'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/migration.rb:621:in `say_with_time'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/migration.rb:641:in `method_missing'
/opt/resource_map/db/migrate/20120615051700_rename_repeat_column_to_site.rb:4:in `change'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/migration.rb:595:in `exec_migration'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/migration.rb:579:in `block (2 levels) in migrate'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/migration.rb:578:in `block in migrate'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/migration.rb:577:in `migrate'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/migration.rb:752:in `migrate'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/migration.rb:991:in `block in execute_migration_in_transaction'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/migration.rb:1039:in `ddl_transaction'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/migration.rb:990:in `execute_migration_in_transaction'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/migration.rb:952:in `block in migrate'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/migration.rb:948:in `each'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/migration.rb:948:in `migrate'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/migration.rb:807:in `up'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/migration.rb:785:in `migrate'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by litlfred** [comment]
Do you need more information to resolve this?

**Comment by mverzilli** [comment]
Hi, Carl! We haven't been able to reproduce the issue... I guess there's something wrong with the environment. 

We're putting together a Vagrant VM with everything ready to run RM, I think that's going to be more straightforward than trying to troubleshoot your particular environment. 

It's almost ready, we just need to test it a little more, but I guess it should be ready before the end of today. Would that work for you?

**Comment by litlfred** [comment]
I guess that Vagrant would be OK, but would like to know how to fix this issue going forward.  Is there an easy way to flush the environment I currently have and restart the install?

BTW, I am on Ubuntu 14.04 for this.

**Comment by mverzilli** [comment]
You could try bundle exec rake db:reset

**Comment by litlfred** [comment]
Thanks.  That seemed to help out.
I noticed that the "rake db:reset" creates the missing index.
<pre>
     -- add_index("reminders", ["repeat_id"], {:name=>"index_reminders_on_repeat_id"})
</pre>
which allowed the "rake db:migrate RAILS_ENV=production" to proceed.

Should the reset be called on a new install, say just after the "script/bundle install --deployment --without=development test" ?   


In any case, I was able to proceed further and got to "passenger start -e production -p 3000".    At this point, pointing my browser at resource map, I get 
<pre>
We're sorry, but something went wrong.
</pre>
with an error code of 500.

Output from passenger is:
<pre>
litlfred@masala:/opt/resource_map$ passenger start -e production -p 3000
=============== Phusion Passenger Standalone web server started ===============
PID file: /opt/resource_map/tmp/pids/passenger.3000.pid
Log file: /opt/resource_map/log/passenger.3000.log
Environment: production
Accessible via: http://0.0.0.0:3000/

You can stop Phusion Passenger Standalone by pressing Ctrl-C.
Problems? Check https://www.phusionpassenger.com/documentation/Users%20guide%20Standalone.html#troubleshooting
===============================================================================
App 26563 stdout: 
App 26563 stderr: /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:216: warning: Insecure world writable dir /opt/resource_map in PATH, mode 040777
[ 2015-01-26 12:03:07.7752 26526/7f0f99ca3700 Pool2/SmartSpawner.h:298 ]: Preloader for /opt/resource_map started on PID 26563, listening on unix:/tmp/passenger.1.0.26522/generation-0/backends/preloader.x0wp3k
App 26584 stdout: 
Started HEAD "/" for 127.0.0.1 at 2015-01-26 12:03:07 -0500
App 26594 stdout: 
Started GET "/" for 192.168.1.33 at 2015-01-26 12:03:08 -0500
Processing by HomeController#index as HTML
Processing by HomeController#index as HTML
Completed 500 Internal Server Error in 16ms

NoMethodError (undefined method `to_h' for {"controller"=>"home", "action"=>"index"}:ActionController::Parameters):
  app/controllers/application_controller.rb:111:in `redirect_to_localized_url'


  Rendered home/index.haml within layouts/application (165.3ms)
  Rendered vendor/bundle/ruby/1.9.1/gems/instedd-rails-0.0.24/app/views/shared/_analytics.html.erb (0.7ms)
  Rendered vendor/bundle/ruby/1.9.1/gems/instedd-rails-0.0.24/app/views/layouts/instedd_application.html.erb (6.3ms)
Completed 200 OK in 209ms (Views: 187.7ms | ActiveRecord: 1.4ms)


Started GET "/" for 192.168.1.33 at 2015-01-26 12:03:19 -0500
Processing by HomeController#index as HTML
Completed 500 Internal Server Error in 1ms

NoMethodError (undefined method `to_h' for {"controller"=>"home", "action"=>"index"}:ActionController::Parameters):
  app/controllers/application_controller.rb:111:in `redirect_to_localized_url'


Started GET "/" for 192.168.1.33 at 2015-01-26 12:03:21 -0500
Processing by HomeController#index as HTML
Completed 500 Internal Server Error in 1ms

NoMethodError (undefined method `to_h' for {"controller"=>"home", "action"=>"index"}:ActionController::Parameters):
  app/controllers/application_controller.rb:111:in `redirect_to_localized_url'

</pre>

**Comment by mverzilli** [comment]
I hit that one recently :). Go to application_controller.rb and replace "to_h" with "to_hash".

**Comment by litlfred** [comment]
should I create a branch/commit/PR?

**Comment by mverzilli** [comment]
I'll push that fix in a while, don't worry. Also, we've been working on bridging the gaps with the recent changes to CSD, and we're putting together a rake script that automates the creation of collections with the sample facilities mandated by IHE for the connectathon (it's a hassle to set up so many layers manually).

**Comment by litlfred** [comment]
There's two parts to that, right? 
1) setting up the schema mapping to CSD
2) loading the sample data

Will 2 be a distinct script from 1, so that we can import multiple data sets?  Here I am thinking in TZ where we likely will want to test out the RM->SHR->HMIS interaction in a test environment we actual TZ data.   Having a "CSD -> rake data loading script" would be very helpful for this.

**Comment by mverzilli** [comment]
Well, kind of. The connectathon mappings won't look like TZ's, so I don't think we'll be able to reuse this. 

TZ is a "real life" dataset, and as such it's a bit more complex. 

The team at TZ will have to define first which fields are going to be exported, then they'll have to figure out how they map to CSD and configure the mappings. 

Anyway, all that process will be transparent for you, because once the mappings are in place it's just a matter of exporting the collection structure and facilities data to your test environment, and that's easy.
