### ISSUE TITLE
Merging CSD Branch into Master

### ISSUE THREAD

**Issue by edjez** [instedd/resourcemap#827]
Need to see merge of CSD API 1.1 branch ( https://github.com/instedd/resourcemap/tree/csd-api-v-1.1 ) into master so automated testing of OHIE workflows can just include this and not require 2 setups of ResourceMap in the same environment.
@steesdale is PM on this, ask him about timelines.

**Comment by nditada** [comment]
Already merged, pending deploy to prod.
