### ISSUE TITLE
Public Collection Redirects to Login Screen

### ISSUE THREAD

**Issue by steesdale** [instedd/resourcemap#829]
I created a collection viewable by anonymous users.  When I log out and then navigate to the collection URL, I am redirected to the login screen. 

Expected: 
I expected to be able to see the collection without having to log in. 

http://resourcemap.instedd.org/en/collections?collection_id=1121

**Comment by steesdale** [comment]
Now it throws an error  
![screen shot 2016-04-27 at 11 03 17 am](https://cloud.githubusercontent.com/assets/3987608/14845575/a941a848-0c67-11e6-826c-dc318d1413ea.png)

**Comment by mmuller** [comment]
Reproducible in version 2.17.2

**Comment by mmuller** [comment]
Working properly in version da54b36
