### ISSUE TITLE
Create New Site Button Missing

### ISSUE THREAD

**Issue by steesdale** [instedd/resourcemap#845]
I Changed Admin settings and then navigated back to the map UI.  The Create New Site Button was missing.  I tried to refresh and it still was missing. 

![screen shot 2015-04-15 at 10 41 21 am](https://cloud.githubusercontent.com/assets/3987608/7162823/6a611404-e35c-11e4-87fa-d2ee2d79a14b.png)

**Comment by ggiraldez** [comment]
This was fixed in 593ed11522b5e0728ad8f6971ea98f71949f5ea7, in particular by [this change](https://github.com/instedd/resourcemap/commit/593ed11522b5e0728ad8f6971ea98f71949f5ea7#diff-492859ea2c19d882760c622be81aec80R7).
