### ISSUE TITLE
Import Wizard Freezes

### ISSUE THREAD

**Issue by steesdale** [instedd/resourcemap#846]
Import wizard is freezing in v2.14.2, never finishes the import process regardless of size/shape of data.

**Comment by steesdale** [comment]
fixed, was a configuration issue.  Thanks @ggiraldez.

**Comment by wirshad** [comment]
Hi @steesdale , I am facing the same issue. What did you change in the configuration? Appreciate your help

**Comment by steesdale** [comment]
Hi - sometimes unicode characters in say a spreadsheets converted to a csv,
can cause issues with the import wizard.  I would check there first.  We
have wanted a better sort of error-handling here for some time, but havnt
been able to get to it yet.  99.9% of the time this has been the cause of
the issue here though.

Let me know if you need any more help.

- Scott
