### ISSUE TITLE
500 server error when deleting a collection's layer or layer field

### ISSUE THREAD

**Issue by pmallol** [instedd/resourcemap#848]
Found in version 2.14.3-pre1

1. Create a Collection
2. Click the wrench button to access settings
3. Go to 'Layers' tab
4. Create Layer X and  Layer Y
5. Delete Layer Y

Obtained: 
A message that reads "Unexpected error ocurred, please refresh the page." and a 500 (Internal Server Error) in the console.

**Comment by bcardiff** [comment]
http://redis.io/commands/scan was added in redis 2.8.0
latest stable available version in servers is redis 2.2
