### ISSUE TITLE
totalPages is not included unless page param is used in api

### ISSUE THREAD

**Issue by bcardiff** [instedd/resourcemap#852]
If a GET is used without `page=` query, the totalPages is null

GET `/api/collections/<ID>.json`
```
{
name: "name",
totalPages: null,
site: [...]
}
```

the expected result should be the same as

GET `/api/collections/<ID>.json?page=1`
```
{
name: "name",
totalPages: 43,
site: [...]
}
```

The sites first page of sites is returned in either case.

found in  v 2.14.5

**Comment by pmallol** [comment]
Ok in Version 2.15-pre1-6-g5f690e6
