### ISSUE TITLE
Notice message of sites with no locations won't disappear after defining locations to all sites

### ISSUE THREAD

**Issue by pmallol** [instedd/resourcemap#855]
Found in Version 2.15-pre1-6-g5f690e6

Preconditions:
There is a collection with a site without a defined location (lat, long) and a notice message appears inside the map when opening said collection

1. Open the collection and click on the option 'Show them' inside the notice message
2. Click on the site without location and define its Location
3. Go back to the collection and refresh the page

Obtained:
The notice for sites with no location won't disappear and clicking again the option to 'Show them' shows no sites without locations

**Comment by pmallol** [comment]
Related to #500

**Comment by mmuller** [comment]
Ok in version 2.17-pre1
