### ISSUE TITLE
Import Wizard Fails

### ISSUE THREAD

**Issue by steesdale** [instedd/resourcemap#856]
I created a new collection (http://resourcemap.instedd.org/en/collections?collection_id=1729&lat=0&lng=0&z=2)  

I then downloaded the data from that collection 

I received many unusual import wizard errors, that in theory should be prevented during data collection. 

I chose to ignore all fields with errors. 

Import still failed. 

Request access to data here: https://drive.google.com/open?id=0B_RUEKy5Lc7BWUNudmhEdGo5Q00

**Comment by asterite** [comment]
I'm currently trying this:

1. Create a new collection
2. Go to the import wizard
3. Upload the CSV that you mention (in the Google Drive)
4. Ignore the error because of the resmap-id column
5. Click "Import"

The data is being imported, I'll come back here when it's done.

Are these the same steps you did?

**Comment by steesdale** [comment]
Slightly different

- Create a collection 
- **Go to Layers, Advanced -> Import layers from collection -> TZ facility registry 
- Upload the CSV that you mention (in the Google Drive)
 - Ignore the error because of the resmap-id column
- Click "Import"

**Comment by asterite** [comment]
@steesdale Thanks, I'll try that.

When you say "Import still failed", what do you mean? The web site says "import failed", there's a crash, or something else?

**Comment by steesdale** [comment]
the wizard said import failed. When I navigate back to the collection only
part of the sites were loaded.   And the RM UI wont present sites.

**Comment by asterite** [comment]
@steesdale Could you send me the exact same file you are trying to upload? Looking at the error logs it seems there are some encoding issues.

However, when I import the file from Google Drive it works fine. Maybe uploading it there and downloading it changes some things in the file, for example fixing some encoding issues to make the file more portable.

So I want to try with the file you are trying with, without going through Google Drive.

**Comment by asterite** [comment]
Well, it seems the database's charset is latin1, not UTF-8. I'm pretty sure that's the issue.

**Comment by asterite** [comment]
However, I was able to import the file from Google Drive, so I'm not sure what the problem is.

In any case, on failures a better error should be reported.

**Comment by steesdale** [comment]
Thanks Ary, this is working now.  No longer a blocker.

- Scott

**Comment by ggiraldez** [comment]
Removing blocker tag

**Comment by steesdale** [comment]
closed
