### ISSUE TITLE
Histories Query Result Incorrect

### ISSUE THREAD

**Issue by steesdale** [instedd/resourcemap#857]
http://resourcemap.instedd.org/api/collections/463/sites/90049/histories.json

When running the query above, the result is for a different collection.  (#409) 

Expected to see result for 463 site number 90049.

**Comment by asterite** [comment]
It seems the collection ID is ignored in that API method (and it seems that in all `/api/collections/{n}/sites` methods).

But why is it a blocker?

**Comment by asterite** [comment]
(not yet deployed)

**Comment by steesdale** [comment]
you are right, not a blocker.
