### ISSUE TITLE
Entering Amharic strings on Members throws internal server error

### ISSUE THREAD

**Issue by mmuller** [instedd/resourcemap#859]
Found in version:
2.16

Preconditions:
There is a Collection 'Foo'

Reproduce steps:
Go to the collection 'Foo'
Navigate to the Members tab
Open the browser console
Fill the email field with the following Amharic string 'ማሩሸስ'

Actual result:
An internal server error is displayed on the browser console 

Expected result:
A message is displayed informing the user that Amharic strings are not supported as email

![screen shot 2016-03-15 at 11 00 45 am](https://cloud.githubusercontent.com/assets/518152/13782399/a947ee8a-eaa5-11e5-98ab-be519b9acc62.png)

**Comment by asterite** [comment]
Fixed: changed users table encoding to utf8. I did this on staging and production.
