### ISSUE TITLE
Identifier fields should not duplicate values of archived sites

### ISSUE THREAD

**Issue by nditada** [instedd/resourcemap#860]
Steps:
Create a collection with an identifier field with Luhn format.
Create a site A
Delete the site A
Create site B

Result:
Site B gets the same Luhn ID as Site A

Expected:
Site B gets a new Luhn ID. Identifier fields should not duplicate values of existing site, even for deleted ones.

**Comment by mmuller** [comment]
Ok in version 2.16.2
