### ISSUE TITLE
Collection/site navigation breaks when using the map

### ISSUE THREAD

**Issue by ggiraldez** [instedd/resourcemap#862]
How to reproduce:

1. Have at least one collection with one site
2. Navigate to a site by clicking on the map icon
3. Press the button to return to the sites list
4. Press the button to return to the collections list
5. Click on a site's icon on the map a second time (can be any site)
6. Press the button to return to the sites list

Expected: the page displays the sites list

Actual: the sites list doesn't show up, the icon turns gray and there is a JS error in the console; actually step 5 will also produce a JS error

JS error in step 5:
```
Uncaught TypeError: Cannot read property 'siteSearchCount' of null
(anonymous function) @ sites_view_model.js?body=1:112
MapViewModel.MapViewModel.showMap @ map_view_model.js?body=1:110
SitesViewModel.SitesViewModel.editSite @ sites_view_model.js?body=1:98
SitesViewModel.SitesViewModel.editSiteFromMarker @ sites_view_model.js?body=1:177
(anonymous function) @ map_view_model.js?body=1:362_.I.trigger @ js?sensor=false&key=&v=3.9:83
(anonymous function) @ marker.js:24_.I.trigger @ js?sensor=false&key=&v=3.9:83
(anonymous function) @ js?sensor=false&key=&v=3.9:31
```

JS error in step 6:
```
sites_view_model.js?body=1:235 Uncaught TypeError: Cannot read property 'fields' of null
SitesViewModel.SitesViewModel.exitSite @ sites_view_model.js?body=1:235
(anonymous function) @ knockout.js?body=1:3714
jQuery.event.dispatch @ jquery.js?body=1:3333
elemData.handle.eventHandle @ jquery.js?body=1:2942
```

**Comment by mmuller** [comment]
Ok in version 2.16.2-15-g98fb1f3
