### ISSUE TITLE
Cancelling the edition of a site doesn't restore the original values

### ISSUE THREAD

**Issue by ggiraldez** [instedd/resourcemap#867]
How to reproduce:
1. Open a collection
2. Go to a site
3. Edit the site
4. Clear the name field
5. Click on "Cancel"

Actual results: the site name disappeared. Even when going back to the site list, the name is blank.

Expected: the site name is restored upon cancelling the edition.

**Comment by mmuller** [comment]
Reproducible in version 2.17.2

**Comment by mmuller** [comment]
Working properly in version da54b36
