### ISSUE TITLE
Unable to search using the complete luhn-id

### ISSUE THREAD

**Issue by bcardiff** [instedd/resourcemap#870]
Searching a luhn id `NNNN-D` will end up with no results.
Search `NNNN` shows the expected result.

![screen shot 2016-07-18 at 11 09 34 am](https://cloud.githubusercontent.com/assets/459923/16917654/df9203be-4cd8-11e6-9fbb-0874a56adb24.png)

![screen shot 2016-07-18 at 11 09 26 am](https://cloud.githubusercontent.com/assets/459923/16917651/dda8c77c-4cd8-11e6-90ba-3efcfd87c3bc.png)

found in: 2.17.1

**Comment by mmuller** [comment]
Reproducible in version 2.17.2

**Comment by mmuller** [comment]
Working properly in version da54b36
