### ISSUE TITLE
Layer Editor - Field Arrows Not Correctly Working

### ISSUE THREAD

**Issue by steesdale** [instedd/resourcemap#874]
We were editing layer fields and wanted to re-order fields and the arrows have some unusual behavior.  Previously we had moved some of the fields into the layer from another. 

![screen shot 2016-09-21 at 12 03 14 pm](https://cloud.githubusercontent.com/assets/3987608/18704701/bd26a282-7ff3-11e6-8077-58c5b9f9ac13.png)

**Comment by steesdale** [comment]
Quick update: by adding a bottom card and clicking up and down on the bottom cards you can unstick the ordering issue.  The average user would most likely will not be able to sort this out though.

**Comment by mmuller** [comment]
@steesdale I couldn’t reproduce this issue in version 2.17.2

**Comment by steesdale** [comment]
Can you send me your email, ill add you to a collection where I can see it happening.

- Scott

**Comment by mmuller** [comment]
@steesdale you can add `mmuller@manas.com.ar` to that collection. Thank you.

**Comment by mmuller** [comment]
I could reproduce the issue using Collections with a large number of fields/layers.

**Comment by mverzilli** [comment]
It's very difficult to reproduce, and even more, when we succeeded at reproducing it was very difficult to tell whether it worked or not, due to poor UX. I think instead of simply fixing this, we should implement drag & drop.

**Comment by mmuller** [comment]
Working properly in version da54b36

**Comment by mverzilli** [comment]
Sorry, I failed to clarify that we implemented DnD for both fields AND layers reordering (cc @mmuller)

**Comment by mmuller** [comment]
@mverzilli fields and layers can be reordered properly.
