### ISSUE TITLE
Zoom Out Button Covered by "There Are Sites w/o Loc" banner

### ISSUE THREAD

**Issue by steesdale** [instedd/resourcemap#881]
Currently if you create a collection and there are sites with missing gps coors, a banner is displayed at the bottom of the map.  The banner currently blocks the zoom out button for the map. 

![screen shot 2016-10-14 at 9 08 51 pm](https://cloud.githubusercontent.com/assets/3987608/19406778/36f45b4c-9253-11e6-9119-086d41e9b892.png)

**Comment by steesdale** [comment]
Ideally - you could also dismiss this bar.   Or we just remove it all together...

**Comment by mmuller** [comment]
Reproducible in version 2.17.2

**Comment by mmuller** [comment]
Working properly in version da54b36
