### ISSUE TITLE
Anonymous User Access to RM UI Not Working

### ISSUE THREAD

**Issue by steesdale** [instedd/resourcemap#883]
**Currently - if I:**
1) Create a collection and provide anonymous access to read all fields
2) log out and reload the collection URL 
3) I see an error -- see below
![screen shot 2016-11-02 at 10 00 40 am](https://cloud.githubusercontent.com/assets/3987608/19934006/424c16b2-a0e3-11e6-88b2-155d5f3b8ddc.png)
4) If I try over the rest API - this is not an issue.  Data is returned as expected. 

**Expected** 
1) A user could see the RM UI w/o logging in.  And interact with the collection as a read only for layers defined in that manner.

**Comment by steesdale** [comment]
**Update**
This error also occur if anonymous access is not enabled - and they follow the URL

**Expected: **
- If a user does not have access to a collection, they should receive a different type of error message.  Perhaps something like "result not found"... you all know better than I.  Currently it comes off as there was a bug in RM.

**Comment by mmuller** [comment]
Duplicate of #829
