### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by lacabra** [instedd/resourcemap#900]
This repository is missing a license, which may prevent others from using it if they don't know under which terms they can use this software.

Most of other repos in this organization have a valid LICENSE file, for example:
https://github.com/instedd/surveda/blob/master/LICENSE
https://github.com/instedd/planwise/blob/master/LICENSE.md
https://github.com/instedd/verboice/blob/master/LICENSE

Thank you!

**Comment by matiasgarciaisaia** [comment]
Good catch!

I'm pretty much sure it's GPLv2 as every app in the InSTEDD Platform, but I'll check & fix 👍

Thanks for letting us know.

**Comment by lacabra** [comment]
@matiasgarciaisaia Thank you for your prompt response!

FYI, I'm working with UNICEF Innovations in the [Digital Public Goods](https://digitalpublicgoods.net) initiative, where we are identifying projects that fit the initial [requirements](https://digitalpublicgoods.net/public-goods/), with plans to subsequently build and support the ecosystem for such projects. I've listed a few from Instedd, which you can review [here](https://digitalpublicgoods.net/candidates). Feel free to submit any edits, or add any other projects that we're missing (either from Instedd or elsewhere!) by way of PRs to this repo: https://github.com/unicef/publicgoods-candidates

Thanks again!

**Comment by matiasgarciaisaia** [comment]
Thanks again for the reminder, @lacabra!

Will take a look at the DPG initiative on Monday 👍
